name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      - name: Lint
        run: npx nx affected -t lint

      - name: Check format
        run: npx nx format:check

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      - name: Run unit tests
        run: npx nx affected -t test

      - name: Generate coverage report
        run: npx nx affected -t test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  build:
    name: Build applications
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      - name: Build affected apps
        run: npx nx affected -t build --exclude=mobile

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Run E2E tests
        run: npx nx affected -t e2e

  notify:
    name: Notify on success
    needs: e2e
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: good
          SLACK_TITLE: Kanora build successful
          SLACK_MESSAGE: 'Kanora has been built and tested successfully!'
